version: "3.9"
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: chat

    ports:
      - 5000:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: "rabbitmq"
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_PASS=password"
      - "RABBITMQ_DEFAULT_USER=username"
    ports:
      - 15672:15672
      - 5672:5672
