version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: chat

    ports:
      - 5000:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
